import { calculateScore, CHARACTER_PROFILES, CONTENT_COUNTS, createGame, createMultiplayerGame, gameViewForPlayer, legalExplorations, legalMoves, reduceGame, TERRAIN_COST, SITES, TOVAK_SKILLS } from './gameEngine';

const act = (state, type, extra={}) => reduceGame(state,{type,...extra});
const cardToHand = (state,id) => {
  const source=state.player.hand.find(c=>c.id===id)?state.player.hand:state.player.deck;
  const i=source.findIndex(c=>c.id===id); const card=source.splice(i,1)[0];
  if(!state.player.hand.includes(card))state.player.hand.push(card); return card;
};

test('base content decks have full-size catalogs',()=>{expect(CONTENT_COUNTS).toEqual({advancedActions:28,spells:20,artifacts:16,units:20,characters:7});});

describe('setup and deterministic state',()=>{
  test('starts a six-round solo conquest with five cards',()=>{const s=createGame(4);expect(s.round).toBe(1);expect(s.time).toBe('day');expect(s.player.hand).toHaveLength(5);expect(s.source).toHaveLength(3);});
  test('same seed creates same deck',()=>expect(createGame(9).player.hand.map(c=>c.id)).toEqual(createGame(9).player.hand.map(c=>c.id)));
  test('terrain table applies day and night inversions',()=>{expect(TERRAIN_COST.day.forest).toBe(3);expect(TERRAIN_COST.night.forest).toBe(5);expect(TERRAIN_COST.day.desert).toBe(5);expect(TERRAIN_COST.night.desert).toBe(3);});
});
describe('deed cards and mana',()=>{
  test('basic action adds points and commits the card',()=>{let s=createGame();const c=cardToHand(s,'march');s=act(s,'PLAY_CARD',{uid:c.uid,mode:'basic'});expect(s.points.move).toBe(2);expect(s.player.played[0].id).toBe('march');});
  test('strong action is rejected without matching mana',()=>{let s=createGame();const c=cardToHand(s,'rage');s=act(s,'PLAY_CARD',{uid:c.uid,mode:'strong'});expect(s.error).toMatch(/requires red/i);expect(s.player.hand.some(x=>x.uid===c.uid)).toBe(true);});
  test('matching crystal powers and is spent',()=>{let s=createGame();const c=cardToHand(s,'rage');s.player.crystals.red=1;s=act(s,'PLAY_CARD',{uid:c.uid,mode:'strong'});expect(s.points.attack).toBe(4);expect(s.player.crystals.red).toBe(0);});
  test('a card may be played sideways',()=>{let s=createGame();const c=s.player.hand[0];s=act(s,'PLAY_CARD',{uid:c.uid,mode:'sideways',as:'influence'});expect(s.points.influence).toBe(1);});
  test('only one Source die per turn',()=>{let s=createGame();s.source[0].color='blue';s.source[1].color='red';s=act(s,'TAKE_SOURCE',{id:s.source[0].id});s=act(s,'TAKE_SOURCE',{id:s.source[1].id});expect(s.error).toMatch(/only one/i);expect(s.mana).toHaveLength(1);});
  test('black Source mana is unusable by day',()=>{let s=createGame();s.source[0].color='black';s=act(s,'TAKE_SOURCE',{id:s.source[0].id});expect(s.error).toMatch(/cannot be used during the Day/i);});
  test('a Spell basic effect requires matching mana',()=>{let s=createGame();const spell={...s.offer.spells[0],uid:'spell-basic'};s.player.hand=[spell];s=act(s,'PLAY_CARD',{uid:spell.uid,mode:'basic'});expect(s.error).toMatch(/casting this Spell requires/i);s.mana=[spell.color];s=act(s,'PLAY_CARD',{uid:spell.uid,mode:'basic'});expect(s.player.played[0].uid).toBe(spell.uid);});
  test('a strong Spell requires Night plus black and matching mana',()=>{let s=createGame();const spell={...s.offer.spells[0],uid:'spell-strong'};s.player.hand=[spell];s.mana=[spell.color,'black'];s=act(s,'PLAY_CARD',{uid:spell.uid,mode:'strong'});expect(s.error).toMatch(/only be cast at Night/i);s.time='night';s=act(s,'PLAY_CARD',{uid:spell.uid,mode:'strong'});expect(s.mana).toEqual([]);expect(s.player.played[0].uid).toBe(spell.uid);});
  test('a strong Artifact is removed from the game without mana',()=>{let s=createGame();const artifact={...s.decks.artifacts[0],uid:'artifact-strong'};s.player.hand=[artifact];s=act(s,'PLAY_CARD',{uid:artifact.uid,mode:'strong'});expect(s.player.removed[0].uid).toBe(artifact.uid);expect(s.player.played).toHaveLength(0);});
});
describe('movement legality',()=>{
  test('adjacent traversable destination includes cost',()=>{const s=createGame();s.points.move=3;const forest=legalMoves(s).find(h=>h.q===1&&h.r===-1);expect(forest.cost).toBe(3);expect(forest.legal).toBe(true);});
  test('moving pays destination cost',()=>{let s=createGame();s.points.move=2;s=act(s,'MOVE',{q:1,r:0});expect([s.player.q,s.player.r]).toEqual([1,0]);expect(s.points.move).toBe(0);});
  test('non-adjacent movement is rejected',()=>{let s=createGame();s.points.move=99;s=act(s,'MOVE',{q:3,r:-3});expect(s.error).toMatch(/adjacent/i);});
  test('enemy space blocks ordinary movement',()=>{let s=createGame();s.player.q=1;s.player.r=0;s.points.move=9;s=act(s,'MOVE',{q:2,r:0});expect(s.error).toMatch(/enemy blocks/i);});
});
describe('combat sequence',()=>{
  const startProwlers=()=>{let s=createGame();s.player.q=1;s.player.r=0;s.points.move=3;return act(s,'START_COMBAT',{q:2,r:-1});};
  test('rampaging enemies are challenged without spending Move',()=>{const s=startProwlers();expect(s.phase).toBe('combat-ranged');expect(s.points.move).toBe(3);});
  test('irrelevant effects cannot be committed during combat',()=>{let s=startProwlers();const c=cardToHand(s,'march');s=act(s,'PLAY_CARD',{uid:c.uid,mode:'basic'});expect(s.error).toMatch(/ranged or siege/i);});
  test('ranged victory leaves hero outside the rampaging enemy hex',()=>{let s=startProwlers();s.points.ranged=3;s=act(s,'RESOLVE_RANGED');expect(s.phase).toBe('action');expect(s.player.fame).toBe(2);expect([s.player.q,s.player.r]).toEqual([1,0]);expect(s.player.reputation).toBe(1);});
  test('fortification ignores ordinary ranged attack',()=>{let s=createGame();s.player.q=1;s.player.r=0;s.points.move=3;s=act(s,'START_COMBAT',{q:2,r:0});s.points.ranged=99;s=act(s,'RESOLVE_RANGED');expect(s.phase).toBe('combat-block');});
  test('swift doubles block requirement',()=>{let s=startProwlers();s=act(s,'RESOLVE_RANGED');s.points.block=4;s=act(s,'RESOLVE_BLOCK');expect(s.combat.blocked).toBe(false);});
  test('unblocked attack deals wounds by armor',()=>{let s=startProwlers();s=act(s,'RESOLVE_RANGED');s=act(s,'RESOLVE_BLOCK');expect(s.player.wounds).toBe(2);});
  test('attack must meet armor',()=>{let s=startProwlers();s=act(s,'RESOLVE_RANGED');s.points.block=8;s=act(s,'RESOLVE_BLOCK');s.points.attack=2;s=act(s,'RESOLVE_ATTACK');expect(s.error).toMatch(/need 3 effective Attack/i);s.points.attack=3;s=act(s,'RESOLVE_ATTACK');expect(s.phase).toBe('action');});
});
describe('sites, turns, and rounds',()=>{
  test('reputation track applies its printed influence modifier',()=>{let s=createGame();s.player.q=0;s.player.r=-1;s.player.reputation=2;s.points.influence=3;s=act(s,'INTERACT',{kind:'recruit',id:'peasants'});expect(s.player.units[0].id).toBe('peasants');expect(s.points.influence).toBe(0);});
  test('village plunder costs reputation and ends turn',()=>{let s=createGame();s.player.q=0;s.player.r=-1;s=act(s,'INTERACT',{kind:'plunder'});expect(s.player.reputation).toBe(-1);expect(s.turn).toBe(2);});
  test('rest discards a wound and ends turn',()=>{let s=createGame();s.player.wounds=1;s.player.hand.push({id:'wound',uid:'w1',name:'Wound'});s=act(s,'REST');expect(s.player.hand.some(c=>c.uid==='w1')).toBe(false);expect(s.turn).toBe(2);});
  test('end turn clears temporary power and draws',()=>{let s=createGame();s.points.move=7;s.player.hand=s.player.hand.slice(0,2);s=act(s,'END_TURN');expect(s.points.move).toBe(0);expect(s.player.hand.length).toBe(5);});
  test('round cannot end while cards remain',()=>{let s=createGame();s.player.deck=[];s=act(s,'END_ROUND');expect(s.error).toMatch(/no playable cards/i);});
  test('valid round end flips day to night',()=>{let s=createGame();s.player.discard.push(...s.player.deck,...s.player.hand);s.player.deck=[];s.player.hand=[];s=act(s,'END_ROUND');expect(s.round).toBe(2);expect(s.time).toBe('night');expect(s.player.hand).toHaveLength(5);});
});

describe('complete base site catalog',()=>{
  test('every declared site is present on the scenario map',()=>{const s=createGame();const present=new Set(s.map.map(h=>h.site).filter(Boolean));expect(Object.keys(SITES).filter(id=>!present.has(id))).toEqual([]);});
  test('adventure sites are entered before combat',()=>{let s=createGame();s.player.q=-2;s.player.r=0;s.points.move=3;s=act(s,'MOVE',{q:-3,r:1});expect([s.player.q,s.player.r]).toEqual([-3,1]);s=act(s,'START_COMBAT',{q:-3,r:1});expect(s.phase).toBe('combat-ranged');expect(s.combat.kind).toBe('adventure');});
  test('a fortified assault pays normal terrain cost and reputation',()=>{let s=createGame();s.player.q=1;s.player.r=0;s.points.move=3;s=act(s,'START_COMBAT',{q:2,r:0});expect(s.points.move).toBe(0);expect(s.player.reputation).toBe(-1);expect(s.combat.kind).toBe('fortified');});
  test('monastery healing costs two Influence',()=>{let s=createGame();s.player.q=2;s.player.r=-2;s.points.influence=2;s.player.wounds=1;s.player.hand.push({id:'wound',uid:'mw'});s=act(s,'INTERACT',{kind:'heal',count:1});expect(s.player.wounds).toBe(0);expect(s.points.influence).toBe(0);});
  test('burning a monastery costs three reputation and starts combat',()=>{let s=createGame();s.player.q=2;s.player.r=-2;s=act(s,'BURN_MONASTERY');expect(s.player.reputation).toBe(-3);expect(s.combat.kind).toBe('burn');});
  test('a conquered mage tower sells a spell for influence and mana',()=>{let s=createGame();const h=s.map.find(x=>x.site==='mage-tower');h.conquered=true;h.enemy=null;s.player.q=h.q;s.player.r=h.r;s.points.influence=7;s.mana=['red'];s=act(s,'INTERACT',{kind:'learn-spell',id:'fireball'});expect(s.player.deck[0].id).toBe('fireball');expect(s.points.influence).toBe(0);});
  test('green city teaches an offered advanced action',()=>{let s=createGame();const h=s.map.find(x=>x.site==='city'&&x.cityColor==='green'),offered=s.offer.advanced[0];h.conquered=true;h.enemy=null;s.player.q=h.q;s.player.r=h.r;s.points.influence=6;s=act(s,'INTERACT',{kind:'learn-advanced',id:offered.id});expect(s.player.deck[0].id).toBe(offered.id);});
  test('red city sells an artifact reward',()=>{let s=createGame();const h=s.map.find(x=>x.site==='city'&&x.cityColor==='red');h.conquered=true;h.enemy=null;s.player.q=h.q;s.player.r=h.r;s.points.influence=12;s=act(s,'INTERACT',{kind:'buy-artifact'});expect(s.pendingRewards[0].type).toBe('artifact');});
  test('white city can add an elite unit',()=>{let s=createGame();const h=s.map.find(x=>x.site==='city'&&x.cityColor==='white');h.conquered=true;h.enemy=null;s.player.q=h.q;s.player.r=h.r;s.points.influence=2;s=act(s,'INTERACT',{kind:'add-elite'});expect(s.offer.units.some(u=>u.elite)).toBe(true);});
  test('mine produces its crystal at end of turn',()=>{let s=createGame();const h=s.map.find(x=>x.site==='mine');s.player.q=h.q;s.player.r=h.r;const before=s.player.crystals[h.mineColor];s=act(s,'END_TURN');expect(s.player.crystals[h.mineColor]).toBe(before+1);});
  test('glade throws away a wound at end of turn',()=>{let s=createGame();const h=s.map.find(x=>x.site==='glade');s.player.q=h.q;s.player.r=h.r;s.player.wounds=1;s.player.discard.push({id:'wound',uid:'gw'});s=act(s,'END_TURN');expect(s.player.wounds).toBe(0);expect(s.mana).toContain('gold');});
  test('adventure rewards must be claimed before turn end',()=>{let s=createGame();s.pendingRewards=[{type:'crystals',count:2,source:'Monster Den'}];s=act(s,'END_TURN');expect(s.error).toMatch(/claim/i);s=act(s,'CLAIM_REWARD',{colors:['red','blue']});expect(s.player.crystals.red).toBe(1);expect(s.player.crystals.blue).toBe(1);});
  test('altar ruins consume matching mana and grant Fame once',()=>{let s=createGame(3);const h=s.map.find(hex=>hex.site==='ruins');s.player.q=h.q;s.player.r=h.r;s.mana=[h.ruinsToken.color];s=act(s,'INTERACT',{kind:'altar'});expect(s.player.fame).toBe(7);expect(h.used||s.map.find(hex=>hex.site==='ruins').used).toBe(true);s=act(s,'INTERACT',{kind:'altar'});expect(s.error).toMatch(/no unused altar/i);});
});

describe('all ten Tovak skills',()=>{
  const withSkills=()=>{const s=createGame();s.player.skills=TOVAK_SKILLS.map(x=>({...x,used:false,roundUsed:false}));return s;};
  test('catalog contains all ten unique skills',()=>{expect(TOVAK_SKILLS).toHaveLength(10);expect(new Set(TOVAK_SKILLS.map(s=>s.id)).size).toBe(10);});
  test('Double Time follows Day and Night values',()=>{let s=withSkills();s=act(s,'USE_SKILL',{id:'double-time'});expect(s.points.move).toBe(2);s=act(s,'END_TURN');s.time='night';s=act(s,'USE_SKILL',{id:'double-time'});expect(s.points.move).toBe(1);});
  test("I Don't Give a Damn boosts one sideways card to two",()=>{let s=withSkills();s=act(s,'USE_SKILL',{id:'i-dont-give-a-damn'});const c=s.player.hand[0];s=act(s,'PLAY_CARD',{uid:c.uid,mode:'sideways',as:'move'});expect(s.points.move).toBe(2);expect(s.bonuses.sideways).toBeNull();});
  test('Who Needs Magic gives three without taking a Source die',()=>{let s=withSkills();s=act(s,'USE_SKILL',{id:'who-needs-magic'});const c=s.player.hand[0];s=act(s,'PLAY_CARD',{uid:c.uid,mode:'sideways',as:'influence'});expect(s.points.influence).toBe(3);});
  test('I Feel No Pain discards a wound and draws',()=>{let s=withSkills();s.player.hand=[{id:'wound',uid:'pain'}];const before=s.player.deck.length;s=act(s,'USE_SKILL',{id:'i-feel-no-pain'});expect(s.player.discard[0].id).toBe('wound');expect(s.player.hand).toHaveLength(1);expect(s.player.deck).toHaveLength(before-1);});
  test('Motivation draws two and grants blue mana once a round',()=>{let s=withSkills();const before=s.player.hand.length;s=act(s,'USE_SKILL',{id:'motivation'});expect(s.player.hand.length).toBe(before+2);expect(s.mana).toContain('blue');s=act(s,'USE_SKILL',{id:'motivation'});expect(s.error).toMatch(/already been used this round/i);});
  test('Mana Overload grants mana and adds four to the powered action',()=>{let s=withSkills();const c=cardToHand(s,'rage');s=act(s,'USE_SKILL',{id:'mana-overload',color:'red'});s=act(s,'PLAY_CARD',{uid:c.uid,mode:'strong'});expect(s.points.attack).toBe(8);});
  test('Night Sharpshooting gives two underground even by Day',()=>{let s=withSkills();const h=s.map.find(x=>x.site==='dungeon');s.player.q=h.q;s.player.r=h.r;s.phase='combat-ranged';s.combat={q:h.q,r:h.r,enemy:h.enemy,kind:'adventure'};s=act(s,'USE_SKILL',{id:'night-sharpshooting'});expect(s.points.ranged).toBe(2);});
  test('Cold Swordsmanship can create Ice Attack',()=>{let s=withSkills();s.phase='combat-attack';s.combat={enemy:{armor:4,traits:[]}};s=act(s,'USE_SKILL',{id:'cold-swordsmanship',mode:'ice'});expect(s.points.iceAttack).toBe(2);});
  test('Shield Mastery supports physical, fire, and ice modes',()=>{for(const mode of ['physical','fire','ice']){let s=withSkills();s.phase='combat-block';s.combat={enemy:{armor:4,traits:[]}};s=act(s,'USE_SKILL',{id:'shield-mastery',mode});expect(s.points[mode==='physical'?'block':`${mode}Block`]).toBe(mode==='physical'?3:2);}});
  test('Resistance Break lowers armor once per resistance',()=>{let s=withSkills();s.phase='combat-ranged';s.combat={enemy:{armor:7,traits:['physical-resistant','fire-resistant']}};s=act(s,'USE_SKILL',{id:'resistance-break'});expect(s.combat.enemy.armor).toBe(5);});
  test('skill level presents two choices and selecting one adds an Advanced Action',()=>{let s=withSkills();s.player.skills=[];s.player.fame=1;s.player.q=1;s.player.r=0;s.points.move=3;s=act(s,'START_COMBAT',{q:2,r:-1});s.points.ranged=3;s=act(s,'RESOLVE_RANGED');expect(s.player.level).toBe(2);expect(s.skillChoices).toHaveLength(2);const chosen=s.skillChoices[0];s=act(s,'SELECT_SKILL',{id:chosen.id});expect(s.player.skills[0].id).toBe(chosen.id);expect(s.player.deck[0].type).toBe('advanced');});
});

describe('round tactics',()=>{
  test('multiplayer games require a day tactic before actions',()=>{let s=createGame(42,{tactics:true});expect(s.phase).toBe('tactic');s=act(s,'SELECT_TACTIC',{id:'early-bird'});expect(s.phase).toBe('action');expect(s.tactic.name).toBe('Early Bird');});
  test('a night tactic cannot be chosen during day',()=>{let s=createGame(42,{tactics:true});s=act(s,'SELECT_TACTIC',{id:'long-night'});expect(s.error).toMatch(/not a day tactic/i);});
  test('chosen tactic has a real once-per-round effect',()=>{let s=createGame(42,{tactics:true});s=act(s,'SELECT_TACTIC',{id:'early-bird'});s=act(s,'USE_TACTIC',{mode:'move'});expect(s.points.move).toBe(2);s=act(s,'USE_TACTIC',{mode:'move'});expect(s.error).toMatch(/already been used/i);});
});

describe('authoritative multiplayer engine',()=>{
  const lobby={id:'ABCD1234',scenario:'full-conquest',players:[{id:'p1',name:'One',character:'tovak'},{id:'p2',name:'Two',character:'arythea'}]};
  test('unique tactics establish shared turn order',()=>{let s=createMultiplayerGame(lobby,42);s=reduceGame(s,{type:'SELECT_TACTIC',id:'planning',playerId:'p1'});s=reduceGame(s,{type:'SELECT_TACTIC',id:'early-bird',playerId:'p2'});expect(s.phase).toBe('action');expect(s.turnOrder).toEqual(['p2','p1']);expect(s.activePlayerId).toBe('p2');});
  test('only the active player can change authoritative state',()=>{let s=createMultiplayerGame(lobby,42);s=reduceGame(s,{type:'SELECT_TACTIC',id:'early-bird',playerId:'p1'});s=reduceGame(s,{type:'SELECT_TACTIC',id:'rethink',playerId:'p2'});const before=s.turn;s=reduceGame(s,{type:'END_TURN',playerId:'p2'});expect(s.turn).toBe(before);expect(s.error).toMatch(/not your turn/i);s=reduceGame(s,{type:'END_TURN',playerId:'p1'});expect(s.activePlayerId).toBe('p2');});
  test('player views keep other hands private',()=>{const s=createMultiplayerGame(lobby,42);const view=gameViewForPlayer(s,'p1');expect(view.player.hand.length).toBeGreaterThan(0);expect(view.players.find(player=>player.id==='p2').hand).toEqual([]);expect(view.players.find(player=>player.id==='p2').handCount).toBeGreaterThan(0);});
  test('a shared explored move is visible in every player view',()=>{let s=createMultiplayerGame(lobby,42);s=reduceGame(s,{type:'SELECT_TACTIC',id:'early-bird',playerId:'p1'});s=reduceGame(s,{type:'SELECT_TACTIC',id:'rethink',playerId:'p2'});s.points.move=4;s=reduceGame(s,{type:'EXPLORE',tileId:'countryside-a',playerId:'p1'});s=reduceGame(s,{type:'MOVE',q:1,r:0,playerId:'p1'});expect(gameViewForPlayer(s,'p2').players.find(player=>player.id==='p1').q).toBe(1);});
  test('round announcement gives every other player one final turn',()=>{let s=createMultiplayerGame(lobby,42);s=reduceGame(s,{type:'SELECT_TACTIC',id:'early-bird',playerId:'p1'});s=reduceGame(s,{type:'SELECT_TACTIC',id:'rethink',playerId:'p2'});s.players.find(player=>player.id==='p1').deck=[];s.players.find(player=>player.id==='p1').hand=[];s=reduceGame(s,{type:'END_ROUND',playerId:'p1'});expect(s.activePlayerId).toBe('p2');expect(s.round).toBe(1);s=reduceGame(s,{type:'END_TURN',playerId:'p2'});expect(s.round).toBe(2);expect(s.phase).toBe('tactic');});
  test('a one-player online game advances directly to the next round',()=>{const solo={...lobby,players:[lobby.players[0]]};let s=createMultiplayerGame(solo,42);s=reduceGame(s,{type:'SELECT_TACTIC',id:'early-bird',playerId:'p1'});s.players[0].deck=[];s.players[0].hand=[];s=reduceGame(s,{type:'END_ROUND',playerId:'p1'});expect(s.round).toBe(2);expect(s.time).toBe('night');expect(s.phase).toBe('tactic');expect(s.activePlayerId).toBeNull();expect(s.tacticPickOrder).toEqual(['p1']);});
});

describe('full multiplayer rules mode',()=>{
  const lobby=scenario=>({id:'FULL1234',scenario,players:[{id:'p1',name:'One',character:'tovak'},{id:'p2',name:'Two',character:'arythea'}]});
  const started=scenario=>{let s=createMultiplayerGame(lobby(scenario),77);s=reduceGame(s,{type:'SELECT_TACTIC',id:'early-bird',playerId:'p1'});return reduceGame(s,{type:'SELECT_TACTIC',id:'rethink',playerId:'p2'});};
  test('multiplayer starts with hidden tiles that can be explored for two Move',()=>{let s=started('full-conquest');expect(legalExplorations(s).some(item=>item.tileId==='countryside-a')).toBe(true);s.points.move=2;s=reduceGame(s,{type:'EXPLORE',tileId:'countryside-a',playerId:'p1'});expect(s.map.filter(hex=>hex.tileId==='countryside-a').every(hex=>hex.revealed)).toBe(true);expect(s.points.move).toBe(0);});
  test('exploration draws deterministic enemies from category stacks',()=>{let a=started('full-conquest'),b=started('full-conquest');for(const state of [a,b])state.points.move=6;a=reduceGame(a,{type:'EXPLORE',tileId:'countryside-a',playerId:'p1'});b=reduceGame(b,{type:'EXPLORE',tileId:'countryside-a',playerId:'p1'});a=reduceGame(a,{type:'MOVE',q:1,r:0,playerId:'p1'});b=reduceGame(b,{type:'MOVE',q:1,r:0,playerId:'p1'});a=reduceGame(a,{type:'EXPLORE',tileId:'countryside-b',playerId:'p1'});b=reduceGame(b,{type:'EXPLORE',tileId:'countryside-b',playerId:'p1'});expect(a.map.find(hex=>hex.site==='rampaging'&&hex.tileId==='countryside-b').enemy.id).toBe(b.map.find(hex=>hex.site==='rampaging'&&hex.tileId==='countryside-b').enemy.id);});
  test('characters have distinct decks and ten distinct skills',()=>{const a=createGame(5,{character:'arythea'}),g=createGame(5,{character:'goldyx'});expect([...a.player.hand,...a.player.deck].map(card=>card.id)).not.toEqual([...g.player.hand,...g.player.deck].map(card=>card.id));Object.values(CHARACTER_PROFILES).forEach(profile=>expect(profile.skills).toHaveLength(10));});
  test('cooperative city assault combines adjacent players',()=>{let s=started('cooperative-conquest');s.map.forEach(hex=>hex.revealed=true);const city=s.map.find(hex=>hex.site==='city');Object.assign(s.players.find(player=>player.id==='p1'),{q:city.q-1,r:city.r});Object.assign(s.players.find(player=>player.id==='p2'),{q:city.q,r:city.r-1});s.points.move=9;s.points.siege=20;s=reduceGame(s,{type:'START_COOPERATIVE_ASSAULT',q:city.q,r:city.r,playerId:'p1'});s=reduceGame(s,{type:'TEAM_CONTRIBUTE',ready:true,playerId:'p1'});s=reduceGame(s,{type:'TEAM_CONTRIBUTE',ready:true,playerId:'p2'});s=reduceGame(s,{type:'RESOLVE_COOPERATIVE_ASSAULT',playerId:'p1'});expect(city.conquered||s.map.find(hex=>hex.q===city.q&&hex.r===city.r).conquered).toBe(true);expect(s.players.every(player=>player.assaults===1)).toBe(true);});
  test('PvP lets the defender react before melee resolves',()=>{let s=started('full-conquest');Object.assign(s.players.find(player=>player.id==='p1'),{q:0,r:0});Object.assign(s.players.find(player=>player.id==='p2'),{q:1,r:0});s.points.attack=6;s=reduceGame(s,{type:'INITIATE_PVP',targetId:'p2',playerId:'p1'});s=reduceGame(s,{type:'PVP_DEFEND',ready:true,playerId:'p2'});s=reduceGame(s,{type:'RESOLVE_PVP',playerId:'p1'});expect(s.phase).toBe('pvp-melee');s=reduceGame(s,{type:'PVP_DEFEND',ready:true,playerId:'p2'});s=reduceGame(s,{type:'RESOLVE_PVP',playerId:'p1'});expect(s.phase).toBe('action');expect(s.players.find(player=>player.id==='p1').pvpWins).toBe(1);});
  test('PvP defender may retreat to a space farther from the attacker',()=>{let s=started('full-conquest');s.map.forEach(hex=>hex.revealed=true);s.map.find(hex=>hex.q===2&&hex.r===0).enemy=null;Object.assign(s.players.find(player=>player.id==='p1'),{q:0,r:0});Object.assign(s.players.find(player=>player.id==='p2'),{q:1,r:0,fame:3});s=reduceGame(s,{type:'INITIATE_PVP',targetId:'p2',playerId:'p1'});s=reduceGame(s,{type:'PVP_RETREAT',q:2,r:0,playerId:'p2'});expect(s.phase).toBe('action');expect(s.pvp).toBeNull();expect(s.players.find(player=>player.id==='p2').fame).toBe(2);});
  test('final scoring includes categories and wound penalties',()=>{const s=createGame();s.player.fame=10;s.player.wounds=2;s.player.units=[{level:2}];const score=calculateScore(s);expect(score.players[0].categories.wounds).toBe(-4);expect(score.players[0].categories.leadership).toBe(2);expect(score.players[0].total).toBe(8);});
  test('units can absorb damage, remain wounded, and consume Heal to recover',()=>{let s=createGame();s.player.units=[{id:'guard',name:'Guard',level:1,armor:3,ability:{block:1},spent:false,wounded:false}];s.player.q=1;s.player.r=0;s=act(s,'START_COMBAT',{q:2,r:-1});s=act(s,'RESOLVE_RANGED');s=act(s,'ASSIGN_DAMAGE_UNIT',{id:'guard'});s=act(s,'RESOLVE_BLOCK');expect(s.player.units[0].wounded).toBe(true);expect(s.player.wounds).toBe(1);s.phase='action';s.points.heal=1;s=act(s,'SPEND_HEAL',{unitId:'guard'});expect(s.player.units[0].wounded).toBe(false);expect(s.points.heal).toBe(0);});
  test('round setup replaces card and unit offers',()=>{let s=createGame();const before=s.offer.advanced.map(card=>card.id);s.player.discard.push(...s.player.deck,...s.player.hand);s.player.deck=[];s.player.hand=[];s=act(s,'END_ROUND');expect(s.offer.advanced.map(card=>card.id)).not.toEqual(before);expect(s.offer.units).toHaveLength(3);});
  test('scenario completion grants all players final turns before scoring',()=>{let s=started('full-conquest');s.map.forEach(hex=>hex.revealed=true);const cities=s.map.filter(hex=>hex.site==='city');cities[0].conquered=true;cities[0].enemy=null;Object.assign(s.players.find(player=>player.id==='p1'),{q:cities[1].q-1,r:cities[1].r});s.points.move=9;s.points.siege=99;s.points.block=99;s.points.attack=99;s=reduceGame(s,{type:'START_COMBAT',q:cities[1].q,r:cities[1].r,playerId:'p1'});s=reduceGame(s,{type:'RESOLVE_RANGED',playerId:'p1'});s=reduceGame(s,{type:'RESOLVE_BLOCK',playerId:'p1'});s=reduceGame(s,{type:'RESOLVE_ATTACK',playerId:'p1'});expect(s.status).toBe('playing');expect(s.scenarioEndTurnsRemaining).toBe(2);s=reduceGame(s,{type:'END_TURN',playerId:'p1'});s=reduceGame(s,{type:'END_TURN',playerId:'p2'});expect(s.status).toBe('won');expect(s.scoring.players).toHaveLength(2);});
  test('players cannot end movement on an occupied non-portal space',()=>{let s=started('full-conquest');s.map.forEach(hex=>hex.revealed=true);Object.assign(s.players.find(player=>player.id==='p2'),{q:1,r:0});s.points.move=9;s=reduceGame(s,{type:'MOVE',q:1,r:0,playerId:'p1'});expect(s.error).toMatch(/another Mage Knight occupies/i);});
  test('movement between two spaces adjacent to a rampaging enemy provokes it',()=>{let s=started('full-conquest');s.map.forEach(hex=>hex.revealed=true);const p1=s.players.find(player=>player.id==='p1');Object.assign(p1,{q:1,r:0});s.points.move=9;s=reduceGame(s,{type:'MOVE',q:1,r:-1,playerId:'p1'});expect(s.error).toMatch(/would provoke/i);});
});
